stages:
  data_ingestion:
    cmd: python youtube_comments_analyzer/data_ingestion.py
    deps:
    - youtube_comments_analyzer/data_ingestion.py
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
    outs:
    - data/raw/raw_data.csv
    - data/raw/train.csv
    - data/raw/test.csv

  data_preprocessing:
    cmd: python youtube_comments_analyzer/data_preprocessing.py
    deps:
    - youtube_comments_analyzer/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim/train.csv
    - data/interim/test.csv

  feature_engineering:
    cmd: python youtube_comments_analyzer/feature_engineering.py
    deps:
    - youtube_comments_analyzer/feature_engineering.py
    - data/interim/train.csv
    - data/interim/test.csv
    params:
    - feature_engineering.ngram_range
    - feature_engineering.max_features
    outs:
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    - data/processed/X_test.csv
    - data/processed/y_test.csv
    - models/vectorizer.pkl
  
  model_training:
    cmd: python youtube_comments_analyzer/model_training.py
    deps:
    - youtube_comments_analyzer/model_training.py
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    params:
    - model_training.learning_rate
    - model_training.min_child_samples
    - model_training.max_depth
    - model_training.n_estimators
    - model_training.objective
    - model_training.num_class
    - model_training.metric
    - model_training.is_unbalance
    - model_training.class_weight
    - model_training.random_state
    - model_training.n_jobs
    outs:
    - models/model.pkl
  
  model_evaluation:
    cmd: python youtube_comments_analyzer/model_evaluation.py
    deps:
    - youtube_comments_analyzer/model_evaluation.py
    - data/processed/X_test.csv
    - data/processed/y_test.csv
    - models/vectorizer.pkl
    - models/model.pkl
    params:
    - model_training.learning_rate
    - model_training.min_child_samples
    - model_training.max_depth
    - model_training.n_estimators
    - model_training.objective
    - model_training.num_class
    - model_training.metric
    - model_training.is_unbalance
    - model_training.class_weight
    - model_training.random_state
    - model_training.n_jobs
    outs:
    - experiment_info.json
    - reports/figures/Confusion_matrix_test.png
  
  model_registration:
    cmd: python youtube_comments_analyzer/model_registration.py
    deps:
    - youtube_comments_analyzer/model_registration.py
    - experiment_info.json
