data_ingestion:
  test_size: 0.20
  random_state: 42

feature_engineering:
  ngram_range: [1, 2]
  max_features: 1000

model_training:
  learning_rate: 0.06747064968662127
  min_child_samples: 10
  max_depth: 30
  n_estimators: 240
  objective: "multiclass"
  num_class: 3
  metric: "multi_logloss"
  is_unbalance: True
  class_weight: "balanced"
  random_state: 42
  n_jobs: -1
