name: CI/CD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.12'
      
      - name: Cache Pip Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install 'dvc[s3]'
      
      - name: Configure DagsHub Authentication
        run: |
          echo "machine dagshub.com login $DAGSHUB_USERNAME password $DAGSHUB_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
        env:
          DAGSHUB_USERNAME: SushrutGaikwad
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}

      - name: Run DVC Pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          RAW_DATA_S3_BUCKET_NAME: ${{ secrets.RAW_DATA_S3_BUCKET_NAME }}
          RAW_DATA_S3_KEY: ${{ secrets.RAW_DATA_S3_KEY }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
          MLFLOW_TRACKING_USERNAME: SushrutGaikwad
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/SushrutGaikwad/youtube-comments-analyzer.mlflow
        run: |
          dvc repro
      
      - name: Confirm MLflow tracking is active
        run: |
          echo "Tracking URI is: $MLFLOW_TRACKING_URI"
          mlflow --version
